
var HP = "76/100";
var lvl = "69";
var STAMINA = "88";
function fillSpacesRight(input, size){
    size -= input.length

    while (size != 0) {
        input = input + ' '
        size--;
    }
    return input
}



console.log("WMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM")
console.log("W                  MWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM")
console.log("W  HP:"+fillSpacesRight(HP, 13)+"MWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM")
console.log("W  STAMINA:"+fillSpacesRight(STAMINA, 8)+"MWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM")
console.log("W  lvl:"+fillSpacesRight(lvl, 12)+"MWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM")
console.log("W                  MWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM")
console.log("WMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM")
console.log("WMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM")
console.log("WMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM                                                             MWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM")
console.log("WMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM          ^                                                  MWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM")
console.log("WMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM         / \__                                                MWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM")
console.log("WMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM        (    @\___                                            MWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM")
console.log("WMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM        /         O                                          MWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM")
console.log("WMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM       /   (_____/                                           MWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM")
console.log("WMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM      /_____/   ||                                           MWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM")
console.log("WMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM"+fillSpacesRight("     | WOOF!|   || ", 57)+"    MWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM")
console.log("WMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM    / \_____/ \\   U                                           MWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM")
console.log("WMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM   /  /     \\  \\                                             MWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM")
console.log("WMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM  |   |     |   |                                            MWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM")                                                   
console.log("WMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM                                                             MWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM")
console.log("WMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM                                                             MWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM")
console.log("WMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM                                                             MWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM")
console.log("WMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM                                                             MWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM")
console.log("WMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM                                                             MWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM")
console.log("WMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM                                                             MWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM")
console.log("WMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM                                                             MWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM")
console.log("WMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM                                                             MWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM")
console.log("WMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM")
console.log("WMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM")
console.log("WMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM WHAT DO YOU DO?   MWMWMWMWMWMWMWMWMWM")
console.log("WMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMW                                                       WMWMWMWMWM  A>PET            MWMWMWMWMWMWMWMWMWM")
console.log("WMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMW                                                       WMWMWMWMWM  B>PET            MWMWMWMWMWMWMWMWMWM")
console.log("WMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMW                                                       WMWMWMWMWM  C>PET            MWMWMWMWMWMWMWMWMWM")
console.log("WMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMW                                                       WMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM")
console.log("WMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMW A WILD DOG APPEARED !                                 WMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM")
console.log("WMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM")
console.log("WMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM")
console.log("WMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM")















"      _-'_'-_       "
"   _-' _____ '-_    "
"_-' ___________ '-_ "
" |___|||||||||___|  "
" |___|||||||||___|  "
" |___|||||||o|___|  "
" |___|||||||||___|  "
" |___|||||||||___|  "
" |___|||||||||___|  "